index:
    path: /
    controller: App\Controller\DefaultController::index
admin:
    path: /admin
    controller: App\Controller\DefaultController::admin
dashboard:
    path: /admin/dashboard
    controller: App\Controller\DefaultController::dashboard
reports:
    path: /admin/relatorios
    controller: App\Controller\DefaultController::reports
login:
    path: /admin/login
    controller: App\Controller\DefaultController::login